POST http://localhost:80/pets HTTP/1.1
Content-Type: application/json

{
    "name": "Rodolfo",
    "age": 7,
    "animalType": "Dog",
    "breed": "Charpey",
    "size": "Small",
    "mood": "Calm"
}